url: "https://marketdata.privatex.io/QueryData"
query_params:
  lastest: "1"
  klineType: "15m"
  pageCount: "1"
  symbol: "BTCUSDT"
headers:
  - "accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
  - "accept-language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6,mt;q=0.5,zh-TW;q=0.4,ja;q=0.3,ko;q=0.2,cs;q=0.1,it;q=0.1,da;q=0.1"
  - "cache-control: max-age=0"
  - "priority: u=0, i"
  - "sec-ch-ua: \"Microsoft Edge\";v=\"131\", \"Chromium\";v=\"131\", \"Not_A Brand\";v=\"24\""
  - "sec-ch-ua-mobile: ?0"
  - "sec-ch-ua-platform: \"macOS\""
  - "sec-fetch-dest: document"
  - "sec-fetch-mode: navigate"
  - "sec-fetch-site: none"
  - "sec-fetch-user: ?1"
  - "upgrade-insecure-requests: 1"
  - "user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0"